#!/bin/bash

x=$(cat /sys/class/backlight/amdgpu_bl0/brightness)
y=$(cat /sys/class/backlight/amdgpu_bl0/max_brightness)

result="$x $y"
#percent=$(echo $result | awk '{printf "%.0f", $1/$2*100}')
echo -n $result | awk '{printf "%.0f", $1/$2*100}'
echo "% "
